spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/storage?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: admin
    initialization-mode: always

app:
  jwt:
    secretKey: JwtSecretKey
    expirationTimeMs: 604800000
  header:
    name: Authorization
    type: "Bearer"